---
title: TITLE TBD

# to produce blinded version set to 1
blinded: 0

authors: 
- name: Lillian Fok
  thanks: The authors gratefully acknowledge Professor Scott LaCombe, Smith College.
  affiliation: Department of Statical & Data Sciences, Smith College
  
- name: Michele Sezgin
  affiliation: Department of Statical & Data Sciences, Smith College

keywords:
- 3 to 6 keywords
- that do not appear in the title

abstract: |
  Twitter has become an increasingly used social networking resource for politicians, social movements, and citizens. Politicians often use twitter to communicate with the public, campaign, advocate for themselves and their policies, and send out calls to action. Twitter has also provided a convenient and public way for the public and organizations to call on elected officials to take action on relevant issues facing the public. We investigate whether state governors twitter habits regarding the Black Lives Matter movement correlates with passage of police reform laws in the state policy diffusion network.

bibliography: bibliography.bib
style: APA
output: rticles::asa_article
---

# Introduction

\(\hspace{.5cm}\) Twitter users often observe elected officials communicating their stance on political issues or making promises of policy change via Twitter. Politicians and their teams invest significant effort into curating a tweets and communicating with the public via online social networking sites. When evaluating the political performance of politicians, we expect that they "practice what they preach" and at least make good-faith attempts to pass legislation regarding issues they have publicly tweeted their support for. However, it is difficult to know whether tweeting about an issue predicts passage of legislation without actively seeking out this information. In the context of the Black Lives Matter movement, politicians were facing unprecedented societal pressure to crack down on police violence and enact substantial police reform laws. Though a controversial issue that saw many bills die in committee in Congress, the states had more power to pass police reform legislation if pursued. This provides the motivation of our work investigating whether tweeting about the Black Lives Matter movement correlates with police reform policy adoption.

# Literature Review

## Politician use of Twitter

\(\hspace{.5cm}\) Social media has become an increasingly pervasive presence in our daily lives and its impact has been far-reaching. Consequently, social media has been increasingly used in a political context. There are several studies regarding the use of social media in general and in a political context. Many studies have focused on the way politicians use social media, finding that common motivations are a desire to grow their support base (sometimes by inciting an extreme reaction), to disseminate information, and to network with other politicians. @Hemsley finds that in the context of the U.S. 2014 gubernatorial election, candidates for governor used Twitter to advocate for themselves, their policies, what they believe in, and calls-to-action in addition to attacks on their opponents and their policies. Further, Hemsley finds that the the most popular tweets that reach the widest audience are call-to-action and attack tweets. Therefore political candidates wishing to broaden their support base may disproportionately send out attack or call-to-action tweets. In the Korean political context, @Park find that Tweets from leading government officials are more likely to increase citizen perceptions of credibility in a government Twitter feeds and government overall. This use of Twitter as a mechanism for politicians to increase trust in government also appears in the U.S., where @Song find that government use of social media websites increases perceived government transparency and citizens’ trust in government. Notably, Song and Lee’s work used 2009 survey data, and may not be consistent with current public perception of government Twitter feeds, and Park et al.’s work may not be applicable in the U.S. political context. Former U.S. president Donald Trump, the highest elected official in the U.S. from 2016-2020, frequently made false or misleading claims on Twitter, and these false or misleading tweets were among his most popular (Rattner, 2021).

\(\hspace{.5cm}\) The way politicians are using Twitter can also be broken down by party, gender, and incumbency, among other factors. @Evans offer a more granular analysis of how politicians are using Twitter in their study of candidates for the 2012 U.S. House. They find that women tweet more overall and are more likely to criticize their opponents. It may be true that female candidates have to work harder to grow their support base, as they are underrepresented in many areas of U.S. government, and may face gender-specific roadblocks to getting elected (Bos et al., 2018). Paired with Hemsley’s findings, it is possible that female political candidates tweet more opponent-criticizing or “attack” messages in an attempt to produce more viral tweets and grow their support base. However, our study focuses on state governor Tweeting during the height of the Black Lives Matter movement, and thus the findings of Evans et al. may not correlate with trends observed in our data. Additionally, our data was not collected during an election cycle, and thus opponent-attacking and campaigning tweets are likely not as prevalent in the dataset. Pivoting to studying politician use of Twitter specific to the BLM movement, @Panda find that in a study of Tweets from 520 U.S. Congress members that Democrats are more likely to tweet about the movement in general and express their concern for police brutality, while Republicans are less likely to tweet about the movement overall and more likely to express concern about perceived protest violence associated with the movement. Because of these findings, we hypothesize that Democratic governors will be more likely to tweet about BLM and police reform overall.

\(\text{Hypothesis}_1: \text{Democratic governors will be more likely to tweet about BLM and police} \\ \text{reform overall.}\)

## Black Lives Matter movement and Twitter

\(\hspace{.5cm}\) The Black Lives Matter (BLM) movement, which peaked in support following the murder of George Floyd, and declined in support from June 2020 - August 2020, has had a steady support level since (Horowitz). Twitter and social media websites played critical roles in helping the movement build momentum during this time period. @Mundt note that Twitter was critical in helping the BLM movement expand and strengthen its internal ties by decreasing roadblocks to organizing and amplifying narratives, among other mechanisms. @Freelon find that BLM, categorized as a powerful Twitter social movement, was correlated with increased mainstream news coverage of issues relevant to the movement, such as police brutality, which is the strongest attention driver for political elites. Americans look to their elected officials for leadership and support regarding contentious and relevant public issues, and this is often portrayed by citizens and organizations communicating with politicians via Twitter and calling on them to take action on important issues. For example, @CTEQI recently tweeted that Congress should revive efforts to pass the Justice in Policing Act, a call to action that is not uncommon among social movements active on Twitter. Additionally, the @BLM tagged Nancy Pelosi in a tweet responding to her commentary on the death of George Floyd, showcasing that Twitter is a direct communication line to public officials that is more convenient and public than traditional methods of citizen-politician communication such as letter-writing or emailing. 

\(\hspace{.5cm}\) Citizens rely on elected officials to implement policy and make change when the public is faced with injustices. When politicians tweet support for certain policies or ideas, this is important, but besides declarations of signing bills into law or cosponsoring legislation, how does the public know if this support holds up when it comes time to vote? For example, @Inslee, governor of the state of Washington, tweeted during the height of the BLM movement’s popularity that Washington’s state government is “going to take a hard look at how we manage independent investigations of police use of force in WA”. However, it is not know empirically whether this show of support resulted in legislative action being taken unless citizens seek it out or he publicly communicates the passage of a law, as Massachusetts governor @Baker and California governor @Newsom did when they passed comprehensive police reform legislation in 2020 and new standards for police use of force in 2019, respectively.

## State Policy Adoption

\(\hspace{.5cm}\) State policy reform is a complex process that cannot be captured by the actions of an individual state governor alone. There has been much scholarship in the field of policy diffusion and investigation of the factors and underlying network that cause states to adopt certain policies. In their study of the correlation between perceived state similarity and similar policy adoption, @Bricker find that factors like perceived state similarity, legislative professionalism, population size differences, and different partisan control of state legislatures can significantly impact whether a state will adopt a policy similar to a policy  previously adopted by another state. @Desmarais model a latent underlying state policy diffusion network that correlates with media state policy emulation stories, finding that California tops the list, especially in more recent years (2005-2009), as a leading policy innovator. In Gavin Newsom’s tweet regarding California’s passage of new standards for police use of force in 2019, he says the passage “[makes California] a model for the rest of the nation”, highlighting that he likely expects the rest of the states to observe the efficacy of this legislation and adopt it if successful. This showcases an important factor in state policy adoption, learning (proposed by @Shipan), in which states may observe policy efficacy in other states before deciding to implement it themselves. Given the results of Desmarais et al. and Governor Newsom’s statement, it is possible that we will find California to be a policy innovator in our network, adopting more police reform policies sooner than other states. Overall, we know that there is non-independence among states regarding choice of policy adoption, which is something we control for in our analysis by treating state policy adoption as a network object.

\(\text{Hypothesis}_2: \text{California will be a policy innovator in our network, adopting police reform} \\ \text{legislation early on in the diffusion process.}\)

## The Relationship Between Twitter and Police-Reform Policy Adoption

\(\hspace{.5cm}\) From the selected studies and tweets, we’ve found that politicians use Twitter for increasing credibility and transparency, building a support base, and communicating their support for policies and ideas, and that Twitter has immense power in helping social movements expand their reach and influence, and communicate with political elites. However, no studies have been found that investigate whether promises made, stances declared, or movements talked about by politicians via Twitter correlate with how they implement policies. We investigate whether tweeting about the Black Lives Matter movement during its peak correlates with police reform policy adoption in U.S. states. We hypothesize that a state governor tweeting about BLM will positively correlate with that state adopting some level of police reform policy.

\(\text{Hypothesis}_3: \text{A state governor tweeting about BLM will positively correlate with that} \\ \text{state adopting some level of police reform policy.}\)

# Methods

\(\hspace{.5cm}\) The first dataset contains full Twitter data of US state governors over the period of May 1, 2020 to October 31, 2020. It was acquired from the open dataset by Zhaozhi Li and Chenglin Zhang from an article titled “Senators’ Response to Black Lives Matter during the 2020 Election Campaign: Evidence from Twitter”. The original web scraping was conducted using the Selenium Python package. The dataset includes 30,490 tweets with the associated governor name, party, Twitter account, time, and text. The text contains the main body of the tweet as well as any hashtags (e.g. #BackTheBlue, #BlackLivesMatter, #COVID19).

The time period of the tweet data overlaps with the murder of George Floyd by police officer Derek Chauvin on May 25, 2020, an event that incited nationwide and global protests in the following months against police brutality, white supremacy, and structural racism under the common message: Black Lives Matter. The demands of these community-led uprisings included calls to “Defund the Police,” restructuring local budgets and law enforcement and instead invest in community programs such as mental health responders, supportive housing, and violence prevention.

Joint methods of key term identification and binary classification were used to label the full set of tweets with the binary designation of content relating to George Floyd, the Black Lives Matter movement, or policing. [more theory here?] From here, we will use “on topic” to refer to text that represents any of these connected topics. 

on_topic <- c('Floyd', 'Breonna', 'Breonna Taylor', 'BLM', 'blm', 'Black Lives Matter', 'lack lives matter', 'protest', 'justice', 'racis', 'law enforcement', 'police', '#BackTheBlue')

off_topic <- c('COVID', 'virus', 'social distanc', 'nurse','hospital', 'health', 'mask', 'testing', 'unemployment', 'schools', 'positive', 'PPE', 'ballot', 'vote', 'census', 'symptom', 'pandemic', 'econom', 'octor')

These were then sub-categorized as aligned with or against the broad demands of the Black Lives Matter movement. Pro- tweets encompassed those sympathetic to George Floyd, Breonna Taylor, and other victims of police brutality; messaging regarding police reforms or defunding; anti-racist and pro-equality statements. Anti- tweets decried the need for mass protest and civil unrest; contained expressions of support for law enforcement; or denigrated the legitimacy of the movement.

We employed a topic classification algorithm using gradient-boosted trees and N-fold cross validation. Topic classification, otherwise known as text classification, is a supervised text mining method and a sub-field of natural language processing (NLP) machine learning. As a supervised The model was trained on a sample of approximately 3,500 hand-labeled tweets. Each instance could be a) on topic, b) pro-BLM/pro-reform/anti-police, and/or c) pro-police/anti-BLM. Most tweets could be categorized into either of the latter two groups.

@(Jay Inslee): “Together, we grieve for the death of George Floyd, and many, many others. The events in Minnesota and across the nation the past few nights have been stunning and illustrate how inequity causes people to lose faith in their public institutions.”

@(Bill Lee): “Approaches that would result in the total upheaval of police are not the right approach to these real and challenging issues. We support law enforcement in Tennessee, and I have the utmost respect for these men and women who serve their communities every day.”

Some politicians expressed sentiments from both groups at the same time. 
@NC_Governor (Roy Cooper): “It’s critical that our state law enforcement be leaders in repairing this breach. They have a tough job and I’m grateful for so many of them who are doing their best to protect and serve with fairness. Many are now acknowledging that systemic and cultural changes must be made.”

Due to the sometimes ambiguous nature and expression of political ideologies, these categories do not fully encompass all that is put forth in a politician’s social media content. A tweet advocating for policing transparency may also encourage additional support for the law enforcement branch making those changes in the same breath. Would such a tweet be aligned with the movement calls for reform, or against the demands for defunding? Such contradictions fall within the mixed goals of a grassroots-organized movement. We ran a binary classification algorithm on each of the three topic groups to annotate tweets with none, one, or multiple labels. 

The state legislative data is sourced from the Brennan Center for Justice, a nonpartisan law and policy institute. The dataset contains records of state-by-state enactment of bills within three areas of policing reform: use of force; duty for officers to intervene, report, or render medical aid in instances of police misconduct; and policies relating to law enforcement misconduct reporting and decertification. All 50 states have adopted some form of legislation relating to at least one of the identified policy areas within the time period of May 25, 2020 to May 21, 2021. The use of force category of bills restricts or specifies the type of physical force police officers are allowed to employ in certain situations. Duty to intervene policies establish responsibility for officers to intervene in cases where they witness use of excessive force, and penalties for failure to do so. Finally, decertification & centralized misconduct reporting bills establish or centralize state misconduct reports that may result in an officer being decertified and removed from duty.

The 50 states are represented as an undirected network, with the degree of similarity between the states among a group of 15 potential policies of policing reform. Similar to policy diffusion networks, weighted ties connect states with shared state policies. We investigate the relationship between our dependent variable of inter-state legislative similarity with independent variable attributes of the social media agenda setting of state governors. We find the frequency of on topic tweeting, relative ratio to total tweets, and amount of positive or negative opinion. While increased frequency is hypothesized to correlate with adoption of legislation, certain legislators produce a much greater volume of tweets than others. The topical makeup of their social media statements may signify legislative priorities, and whether or not that politician is highly motivated to take action on issues of criminal justice. 

